### PR TITLE
87 fix plant creation bug

### LINKED ISSUE #87: Remove species from plant model validation to fix plant creation bug

### PR DESCRIPTION
**Pull request by AngelaGuardia**
fixes #87 

Removes all validations except for name and description. This allows plants coming in with some missing fields from the plant-microservice to be added to the database.

### CODE REVIEW

File: app/models/plant.rb [hunk 1]
```diff
@@ -1,5 +1,5 @@
 class Plant < ApplicationRecord
-  validates :image, :name, :species, :description, :light_requirements, :water_requirements, :when_to_plant, :harvest_time, :common_pests, presence: true
+  validates :name, :description, presence: true
```
Comment (drewwilliams5280) [inline app/models/plant.rb:2]: Perfect!
